[package]
name = "rust_sqlite"
version = "0.1.0"
authors = ["Joao Henrique Machado Silva <joaoh82@gmail.com>"]
edition = "2018"
description = "Light version of SQLite developed with Rust"
repository = "https://github.com/joaoh82/rust_sqlite"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.1.0"
log = "0.4.14"
env_logger = "0.8.3"
rustyline-derive = "0.4.0"
clap = "2.33.3"
sqlparser = "0.8.0"